[[section-introduction-and-goals]]
==	Einführung und Ziele

Dieses Kapitel ist unterteilt in eine kurze Beschreibung und Extrakt der Requirements im Abschnitt <<Aufgabenstellung>>, sowie einer Aufzählung der relevantesten Qualitätsziele für die Architektur in <<Qualitätsziele>>, deren Erreichung für die wichtigsten Stakeholder kritisch ist. Zuletzt erfolgt in <<Stakeholder>> eine Übersicht über die wichtigsten Stakeholder mit deren Erwartungen bezüglich der Architektur.

=== 1.1. Aufgabenstellung (Requirements Overview)

Um die Aufgabenstellung für dqualizer zu erläutern wird im Folgenden die Vorhabenskurzbeschreibung footnote:[Dokument: "Domänenzentrierte Laufzeitqualitätsanalyse geschäftskritischer Anwendungssysteme"] zitiert:

"Das Forschungsvorhaben dqualizer der Novatec Consulting GmbH und der Universität Hamburg hat
das Ziel, diese Kluft zwischen der Fachlichkeit der Anwendungssysteme und den (technischen) Maßnahmen
und Erkenntnissen der Qualitätssicherung durch einen domänenzentrierten Ansatz zu schließen.

Hierzu sollen Möglichkeiten zur Modellierung und Überwachung von Belangen der Laufzeitqualität in DDD-basierte
Techniken integriert werden. Aus fachlicher Perspektive lassen sich durch dqualizer automatisiert aussagekräftige Last- und Resilienztests erzeugen und interpretieren sowie die Verbindungen zum technischen
Monitoring herstellen.

Die entwickelten innovativen Konzepte sollen in einem Open-Source-Werkzeug umgesetzt
und in Anbindung an existierende Werkzeuge verfügbar und nutzbar gemacht werden."

=== 1.2. Qualitätsziele (Quality goals)

Dieser Abschnitt untermalt die Qualitätsziele der Architektur des dqualizer Projektvorhabens. Hierzu wird auf das Kapitel "1.3 Wissenschaftliche und/oder technische Arbeitsziele des Vorhabens" verwiesen.

[cols="1,2" options="header"]
|===
|Qualitätsziel |Beschreibung

|Qualitätsziel 1 formuliert
|Qualitätsziel 1 formuliert als Text

|Qualitätsziel 2 formuliert
|Qualitätsziel 2 formuliert als Text


|Qualitätsziel 3 formuliert
|Qualitätsziel 3 formuliert als Text

|===


=== 1.3. Stakeholder

//Kommentar: Assoziierte Anwendungs- und Transferpartner. Die DATEV eG und die VHV solutions GmbH.
Es folgt eine Übersicht über die wichtigsten Stakeholder mit deren Erwartungen bezüglich der Architektur. Die Stakeholder sind dabei einem Workshop Miro Board.footnote:[https://miro.com/app/board/uXjVOAAmeeo=/] entnommen.


Es erfolgt eine Übersicht über fachliche und (IT-) technische Stakeholder, sowie eine Beschreibung der jeweiligen Erwartungshaltung.

[cols="1,2" options="header"]
|===
|Rolle |Erwartungshaltung
|Manager | Als Manager möchte ich wissen welche Auswirkungen sich eine ändernde Kundenanzahl auf IT Ressourcen hat, um die Kosten besser abschätzen zu können.
|Fach Product Owner | Als Fach Product Owner möchte ich mit wenig Aufwand die Qualitätsanforderungen des Fachexperten erfassen und bewerten.
|Fachexperte | Als Fachexperte möchte ich Qualitätsanforderungen und -szenarien anhand meiner modellierten Prozesse definieren.
|===


[cols="1,2" options="header"]
|===
|Rolle |Erwartungshaltung
| DevOps-Fachkraft | Als ...
| Operations-Fachkraft | Als ...
| Development-Fachkraft | Als ...
| Software Architekt | Als ...
| Fachlicher Tester | Als ...
|===

